import { motion } from 'framer-motion';
import { Card } from '../../components/ui/Card';
import { AchievementBadge, ClassCard, ExamCard, HomeworkCard, NotificationCard, ProgressCard, QuickActionCard, StatCard } from './components/DashboardCards';
import { achievements, classes, dailySummary, exams, homework, learningTwinSummary, notifications, progress, quickActions, stats, studentName } from './data/studentDashboardData';

export function StudentDashboardPage() {
  return <div className="py-8 sm:py-12"><motion.section initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} className="rounded-[2rem] bg-gradient-to-br from-brand to-aqua p-6 text-white shadow-2xl shadow-brand/20 sm:p-8"><p className="font-semibold text-white/80">Student Dashboard</p><h1 className="mt-2 text-4xl font-black sm:text-5xl">Welcome back, {studentName}.</h1><p className="mt-4 max-w-2xl text-white/85">{dailySummary}</p></motion.section>
    <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{stats.map((stat) => <StatCard key={stat.label} stat={stat} />)}</section>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1.35fr_0.65fr]"><div className="grid gap-6"><Card><h2 className="text-2xl font-black text-ink">Learning Twin summary</h2><p className="mt-3 text-muted">{learningTwinSummary}</p></Card><Card><h2 className="text-2xl font-black text-ink">Weekly progress overview</h2><div className="mt-5 grid gap-4 md:grid-cols-3">{progress.map((metric) => <ProgressCard key={metric.label} metric={metric} />)}</div></Card><Card><h2 className="text-2xl font-black text-ink">Today&apos;s classes</h2><div className="mt-5 grid gap-3 md:grid-cols-3">{classes.map((item) => <ClassCard key={item.subject} item={item} />)}</div></Card><Card><h2 className="text-2xl font-black text-ink">Homework</h2><div className="mt-5 grid gap-3 md:grid-cols-2">{homework.map((item) => <HomeworkCard key={item.title} item={item} />)}</div></Card></div><aside className="grid gap-6"><Card><h2 className="text-xl font-black text-ink">Upcoming exams</h2><div className="mt-4 grid gap-3">{exams.map((item) => <ExamCard key={item.subject} item={item} />)}</div></Card><Card><h2 className="text-xl font-black text-ink">Achievement badges</h2><div className="mt-4 grid grid-cols-2 gap-3">{achievements.map((item) => <AchievementBadge key={item.title} item={item} />)}</div></Card><Card><h2 className="text-xl font-black text-ink">Notifications</h2><div className="mt-4 grid gap-3">{notifications.map((item) => <NotificationCard key={item.title} item={item} />)}</div></Card><Card><h2 className="text-xl font-black text-ink">AI quick actions</h2><div className="mt-4 grid gap-3">{quickActions.map((item) => <QuickActionCard key={item.title} item={item} />)}</div></Card></aside></div></div>;
}
