import type { ChatMessage, LearningTwinInsights } from '../types/learningTwin';

export function InsightPanel({ insights }: { insights: LearningTwinInsights }) {
  return <aside className="grid gap-4"><Metric label="Confidence" value={insights.confidenceScore} /><Metric label="Attention" value={insights.attentionLevel} /><Info title="Learning style" value={insights.learningStyle} /><Info title="Next lesson" value={insights.recommendedNextLesson} /><List title="Strengths" items={insights.strengths} /><List title="Weaknesses" items={insights.weaknesses} /><List title="Study recommendations" items={insights.studyRecommendations} /></aside>;
}
function Metric({ label, value }: { label: string; value: number }) { return <section className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex justify-between"><h3 className="font-bold text-ink">{label}</h3><span className="font-black text-brand">{value}%</span></div><div className="mt-3 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-brand to-aqua" style={{ width: `${value}%` }} /></div></section>; }
function Info({ title, value }: { title: string; value: string }) { return <section className="rounded-3xl bg-white p-5 shadow-sm"><h3 className="font-bold text-ink">{title}</h3><p className="mt-2 text-sm text-muted">{value}</p></section>; }
function List({ title, items }: { title: string; items: string[] }) { return <section className="rounded-3xl bg-white p-5 shadow-sm"><h3 className="font-bold text-ink">{title}</h3><ul className="mt-3 grid gap-2 text-sm text-muted">{items.map((item) => <li key={item}>• {item}</li>)}</ul></section>; }
export function ChatBubble({ message }: { message: ChatMessage }) { const isStudent = message.role === 'student'; return <article className={`max-w-[85%] rounded-3xl px-4 py-3 ${isStudent ? 'ml-auto bg-brand text-white' : 'bg-white text-ink shadow-sm'}`}><p>{message.content}</p></article>; }
export function ThinkingAnimation() { return <div className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-semibold text-muted shadow-sm" role="status"><span className="size-2 animate-bounce rounded-full bg-brand" /><span className="size-2 animate-bounce rounded-full bg-aqua [animation-delay:120ms]" /><span className="size-2 animate-bounce rounded-full bg-sun [animation-delay:240ms]" />Learning Twin is thinking</div>; }
